version: "3.7"
services:
  pocketbase:
    build: .
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8090"
    volumes:
      - "${DATA_VOLUME}:/pb_data"
      - "${PUBLIC_VOLUME}:/pb_public"
      - "${MIGRATIONS_VOLUME}:/migrations"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  store:
    driver: local
