version: "3.7"
services:
  pocketbase:
    build: .
    container_name: pocketbase-backend
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:8090"
    volumes:
      - type: bind
        source: ${DATA_VOLUME}
        target: /pb_data
        is_directory: true
      - type: bind
        source: ${PUBLIC_VOLUME}
        target: /pb_public
        is_directory: true
      - type: bind
        source: ${MIGRATIONS_VOLUME}
        target: /migrations
        is_directory: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
