global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # PocketBase metrics
  - job_name: 'pocketbase'
    static_configs:
      - targets: ['pocketbase:9091']
      # - targets: ['host.docker.internal:9091']

  # Node Exporter metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
